FROM node:18-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y openssl libc6-dev curl

COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY prisma ./prisma/
COPY . .

RUN npx prisma generate

EXPOSE 5000

CMD ["npm", "run", "dev"]
